version: 2.1

jobs:
  build:
    working_directory: ~/
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test
    steps:
      - checkout
      - run: python3 main-test.py
  
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
    