version: 2.1
jobs:
  build:
    working_directory: ~/circleci-node
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test
    steps:
      - checkout
      - run: |
          docker build -t node-tst .
  test:
    working_directory: ~/circleci-node
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test
    steps:
      - checkout
      - run: |
          npm i
          npm test
  deploy:
    working_directory: ~/circleci-node
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test
    steps:
      - checkout
      - run: |
          docker run -p 3000:3000 -d node-tst
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /^node.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /^node.*/
      - hold:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              only: /^node.*/
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: /^node.*/