version: 2.1

jobs:
  build:
    working_directory: ~/circleci-node
    machine: true
    resource_class: neetesshhr/aws-runnerr
    steps:
      - checkout
      - run: |
          docker build -t node-tst .

  test:
    working_directory: ~/circleci-node
    machine: true
    resource_class: neetesshhr/aws-runnerr
    steps:
      - checkout
      - run: |
          npm i
          npm test

  deploy:
    working_directory: ~/circleci-node
    machine: true
    resource_class: neetesshhr/aws-runnerr
    steps:
      - checkout
      - run: |
          docker run -p 3000:3000 -d node-tst

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /^node.*/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /^node.*/
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: /^node.*/
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: /^node.*/
