version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test

    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test

    steps:
      - checkout
      - run: python3 main-test.py
  
  deploy:
    working_directory: ~/circleci-python
    machine: true
    resource_class: kzexu9zaxcq5tjmkujg44l/test
    steps:
      - checkout
      - run: python3 main-deploy.py
  
workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /^python.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^python.*/
            branches:
              ignore: /.*/
      - hold:
          type: approval
          requires:
            - build
            - test
          filters:
            tags:
              only: /^python.*/
            branches:
              ignore: /.*/

      - deploy:
          requires:
            - hold
          filters:
            tags:
              only: /^python.*/
            branches:
              ignore: /.*/
      
    